### ISSUE TITLE
Latest binary contains old version?

### ISSUE THREAD

**Issue by IngoValente** [prisma/homebrew-prisma#14]
Just updated prisma with homebrew, and looks like I received version 1.21.1 instead of 1.27.0.

To check, I manually downloaded binaries from:
```https://homebrew-prisma.s3.eu-west-1.amazonaws.com/prisma-1.27.0.tar.gz```
and the previous version:
```https://homebrew-prisma.s3.eu-west-1.amazonaws.com/prisma-1.26.4.tar.gz```

After unzipping and running both to check their versions I get the correct version for 1.26.4, but an old version for 1.27.0:
![screenshot 2019-02-23 at 10 27 20](https://user-images.githubusercontent.com/4366126/53284516-deba2600-3755-11e9-97bb-7c91e3897673.png)

**Comment by divyenduz** [comment]
The version is misleading, there was a bug that stopped the version from being updated in the latest binary but the code is latest. That bug is now fixed. 

You can update using `brew upgrade prisma`
